- name: set up catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: Add application User
    ansible.builtin.user:
      name: roboshop
      comment: roboshop system user
      system: true #this means system user
      shell: /sbin/nologin
      home: /app 

# how does the idempotency check happens here? --> in linux,shell we should explicitly check whether user is present or not, we should create user only if dosen't exists. But in ansible by default it is idempotenet ansible handles this, hence ansible in background checks whether user exists or not and will only create only if user is not present

  - name: create a directory if dosen't exists
    ansible.builtin.file:
      state: directory
      path: /app
      
  - name: download DEV written code - catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip 

  - name: extract catalogue application - unzipping
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app 
      remote_src: yes

  - name: install dependencied - npm install
    community.general.npm:
      path: /app/ 

  - name: copying .service file
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

# we should do daemon reload, start and enable, but since we have dependecies on the database we will first do that configuration

  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client in order to acess to database
    ansible.builtin.package:
      name: mongodb-mongosh
      state: present

  - name: connnect to mongodb catalogue
    ansible.builtin.command: mongosh mongodb.daws86s.fun --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
    register: catalogue_output

  # - name: evaluate catalogue database
  #   community.mongodb.mongodb_shell:
  #     login_host: mongodb.akshaysunny.space
  #     eval: db.getMongo().getDBNames().indexOf('catalogue')
  #   register: catalogue_output

  # we will print the catalogue_output and then we will decide whether we should create db (if not created early) or ignore (if db already existed).
  # - name: print catalogue output
  #   ansible.builtin.debug:
  #     msg: "The catalogue output is: {{ catalogue_output }}"

  - name: load products into mongodb
    ansible.builtin.shell: mongosh --host mongodb.daws86s.fun </app/db/master-data.js
    when: catalogue_output.stdout | int < 0

  
