[frontend]
172.31.23.32

[mongodb]
mongodb.daws86s.fun

[catalogue]
catalogue.daws86s.fun

[mysql]
mysql.daws86s.fun

[redis]
redis.daws86s.fun

[rabbitmq]
rabbitmq.daws86s.fun

[user]
user.daws86s.fun

[cart]
cart.daws86s.fun

[local]
localhost


[all:vars] #for all servers which we are connecting these are user,password -> now no need to mention in cmd
ansible_user=ec2-user
ansible_password=DevOps321
